'use client'
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/core/Navbar";
import { RecoilRoot } from "recoil";
import Head from "next/head";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>RPR</title>
        <meta name="description" content="Description of your app" />
      </Head>
      <body className={inter.className}>
        <RecoilRoot>
          <Providers>
            <Toaster />
            <Navbar />
            {children}
          </Providers>
        </RecoilRoot>
      </body>
    </html>
  );
}
